In [4]:
import pandas as pd
import numpy as np
import openpyxl

In [6]:
march = pd.read_excel("../1.data/1.raw/compras_marco.xlsx")
print(march.shape)
march.head()

(76961, 18)

,id_compra,score_1,score_2,score_3,score_4,score_5,score_6,pais,score_7,produto,categoria_produto,score_8,score_9,score_10,data_compra,valor_compra,score_fraude_modelo,fraude
0,1,4,0.7685,94436.24,20.0,0.444828,1.0,BR,5,Máquininha Corta Barba Cabelo Peito Perna Pelo...,cat_8d714cd,0.883598,240.0,102.0,2020-03-27 11:51:16,5.64,66,0
1,3,4,0.7455,242549.09,3.0,0.000000,19.0,AR,23,Bicicleta Mountain Fire Bird Rodado 29 Alumini...,cat_e9110c5,0.516368,1779.0,77.0,2020-03-25 18:13:38,339.32,95,0
2,7,4,0.5962,7121.78,2.0,0.398000,0.0,BR,11,"Corpinho Avulso Joseph, Josepha Ou Placa Sem Sexo",cat_5d6059e,0.204991,127.0,125.0,2020-03-22 19:20:24,10.56,71,0
3,10,4,0.4759,40143.12,50.0,0.000000,41.0,AR,3,Gamepad Joystick Para Telefono Celular Android...,cat_5d79fb9,0.735790,4701.0,940.0,2020-03-11 15:06:38,30.48,60,0
4,11,4,0.8353,121926.06,39.0,0.186957,34.0,BR,24,Escova Dental Curaprox 5460 Ultra Soft Com 3 U...,cat_4744ece,0.943792,3248.0,132.0,2020-03-15 19:18:50,14.85,10,0

In [8]:
april = pd.read_csv("../1.data/1.raw/compras_abril.csv", sep=";", decimal=",")
print(april.shape)
april.head()

(73289, 18)

,id_compra,score_1,score_2,score_3,score_4,score_5,score_6,pais,score_7,produto,categoria_produto,score_8,score_9,score_10,data_compra,valor_compra,score_fraude_modelo,fraude
0,102932,4,0.7996,94361.39,7.0,1.301818,5.0,BR,6,Mini Lixas De Unha P/ Manicure 144 Un Preta --...,cat_38c78b7,0.088398,1662.0,92.0,2020-04-06 16:45:30,2.69,84,0
1,143765,2,0.4208,5152.84,10.0,0.000000,13.0,AR,7,Fuente Switching 12v 3a Camara Cctv Tira De Le...,cat_f4f8e96,0.303513,3334.0,132.0,2020-04-09 15:13:33,5.89,22,0
2,41481,4,0.7292,7997.69,3.0,0.665675,1.0,BR,9,Kit 10 Calcinhas Menina Infantil De Algodão La...,cat_c20125f,0.565449,1519.0,43.0,2020-04-09 13:35:33,5.13,77,0
3,61515,4,0.7689,75029.18,50.0,0.073589,111.0,BR,13,Coletor 4x1 Motor Ap C/ Piramide De Fluxo Sem ...,cat_57ac90b,0.343432,5086.0,1672.0,2020-04-16 08:58:44,80.56,48,0
4,106496,4,0.7708,112238.17,50.0,0.000000,59.0,BR,48,Tinta Para Pincel Atomico Tr37 Vermelho Pilot ...,cat_449303c,0.836338,4383.0,498.0,2020-04-02 12:57:43,9.47,8,0

In [9]:
march.info()

<class 'pandas.DataFrame'>
RangeIndex: 76961 entries, 0 to 76960
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_compra            76961 non-null  int64
 1   score_1              76961 non-null  int64
 2   score_2              64640 non-null  float64
 3   score_3              64640 non-null  float64
 4   score_4              76710 non-null  float64
 5   score_5              76961 non-null  float64
 6   score_6              76953 non-null  float64
 7   pais                 76919 non-null  str
 8   score_7              76961 non-null  int64
 9   produto              76961 non-null  object
 10  categoria_produto    76961 non-null  str
 11  score_8              76961 non-null  float64
 12  score_9              76953 non-null  float64
 13  score_10             76710 non-null  float64
 14  data_compra          76961 non-null  datetime64[us]
 15  valor_compra         76961 non-null  float64
 16  score_fraude_modelo  76961 non-null  int64
 17  fraude               76961 non-null  int64
dtypes: datetime64[us](1), float64(9), int64(5), object(1), str(2)
memory usage: 10.6+ MB

In [10]:
april.info()

<class 'pandas.DataFrame'>
RangeIndex: 73289 entries, 0 to 73288
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_compra            73289 non-null  int64
 1   score_1              73289 non-null  int64
 2   score_2              72625 non-null  float64
 3   score_3              72625 non-null  float64
 4   score_4              73174 non-null  float64
 5   score_5              73289 non-null  float64
 6   score_6              73286 non-null  float64
 7   pais                 73135 non-null  str
 8   score_7              73289 non-null  int64
 9   produto              73289 non-null  str
 10  categoria_produto    73289 non-null  str
 11  score_8              73289 non-null  float64
 12  score_9              73286 non-null  float64
 13  score_10             73174 non-null  float64
 14  data_compra          73289 non-null  str
 15  valor_compra         73289 non-null  float64
 16  score_fraude_modelo  73289 non-null  int64
 17  fraude               73289 non-null  int64
dtypes: float64(9), int64(5), str(4)
memory usage: 10.1 MB

In [11]:
april['data_compra']

0        2020-04-06 16:45:30
1        2020-04-09 15:13:33
2        2020-04-09 13:35:33
3        2020-04-16 08:58:44
4        2020-04-02 12:57:43
                ...
73284    2020-04-03 00:18:37
73285    2020-04-03 08:22:38
73286    2020-04-07 09:43:27
73287    2020-04-19 08:48:16
73288    2020-04-19 07:28:17
Name: data_compra, Length: 73289, dtype: str

In [12]:
march['data_compra']

0       2020-03-27 11:51:16
1       2020-03-25 18:13:38
2       2020-03-22 19:20:24
3       2020-03-11 15:06:38
4       2020-03-15 19:18:50
                ...
76956   2020-03-17 13:36:18
76957   2020-03-11 20:21:35
76958   2020-03-11 19:36:07
76959   2020-03-16 07:13:24
76960   2020-03-26 08:47:12
Name: data_compra, Length: 76961, dtype: datetime64[us]

In [14]:
documents = pd.read_json("../1.data/1.raw/documentos.json")
print(documents.shape)
documents.head()

(150000, 4)

   idCompra  doc1 doc2 doc3
0         1     1  NaN    N
1         2     1    Y    N
2         3     1  NaN    N
3         4     1  NaN    Y
4         5     1  NaN    N

In [15]:
documents.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   idCompra  150000 non-null  int64
 1   doc1      150000 non-null  int64
 2   doc2      41143 non-null   str
 3   doc3      150000 non-null  str
dtypes: int64(2), str(2)
memory usage: 4.6 MB

In [16]:
## renomeando colunas - método .rename()
colunas = {
    "idCompra": "id_compra",
    "doc1": "entrega_doc_1",
    "doc2": "entrega_doc_2",
    "doc3": "entrega_doc_3"
}

documents = documents.rename(columns=colunas)
documents.head()

   id_compra  entrega_doc_1 entrega_doc_2 entrega_doc_3
0          1              1           NaN             N
1          2              1             Y             N
2          3              1           NaN             N
3          4              1           NaN             Y
4          5              1           NaN             N

## Junção dos dados (como no SQL)

In [18]:
## método concat() - concatenando os dataframes march e april
df_march_april = pd.concat([march, april], ignore_index=True)
print(df_march_april.shape)
df_march_april.head()

(150250, 18)

,id_compra,score_1,score_2,score_3,score_4,score_5,score_6,pais,score_7,produto,categoria_produto,score_8,score_9,score_10,data_compra,valor_compra,score_fraude_modelo,fraude
0,1,4,0.7685,94436.24,20.0,0.444828,1.0,BR,5,Máquininha Corta Barba Cabelo Peito Perna Pelo...,cat_8d714cd,0.883598,240.0,102.0,2020-03-27 11:51:16,5.64,66,0
1,3,4,0.7455,242549.09,3.0,0.000000,19.0,AR,23,Bicicleta Mountain Fire Bird Rodado 29 Alumini...,cat_e9110c5,0.516368,1779.0,77.0,2020-03-25 18:13:38,339.32,95,0
2,7,4,0.5962,7121.78,2.0,0.398000,0.0,BR,11,"Corpinho Avulso Joseph, Josepha Ou Placa Sem Sexo",cat_5d6059e,0.204991,127.0,125.0,2020-03-22 19:20:24,10.56,71,0
3,10,4,0.4759,40143.12,50.0,0.000000,41.0,AR,3,Gamepad Joystick Para Telefono Celular Android...,cat_5d79fb9,0.735790,4701.0,940.0,2020-03-11 15:06:38,30.48,60,0
4,11,4,0.8353,121926.06,39.0,0.186957,34.0,BR,24,Escova Dental Curaprox 5460 Ultra Soft Com 3 U...,cat_4744ece,0.943792,3248.0,132.0,2020-03-15 19:18:50,14.85,10,0

### métodos de junção como o sql - merge()

`left` 

`right`

`inner` 

`outer`

In [19]:
## método .merge() - unindo os dataframes df_march_april e documents
df_completo = pd.merge(df_march_april, documents, how="left", on="id_compra")
df_completo.info()

<class 'pandas.DataFrame'>
RangeIndex: 150250 entries, 0 to 150249
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id_compra            150250 non-null  int64
 1   score_1              150250 non-null  int64
 2   score_2              137265 non-null  float64
 3   score_3              137265 non-null  float64
 4   score_4              149884 non-null  float64
 5   score_5              150250 non-null  float64
 6   score_6              150239 non-null  float64
 7   pais                 150054 non-null  str
 8   score_7              150250 non-null  int64
 9   produto              150250 non-null  object
 10  categoria_produto    150250 non-null  str
 11  score_8              150250 non-null  float64
 12  score_9              150239 non-null  float64
 13  score_10             149884 non-null  float64
 14  data_compra          150250 non-null  object
 15  valor_compra         150250 non-null  float64
 16  score_fraude_modelo  150250 non-null  int64
 17  fraude               150250 non-null  int64
 18  entrega_doc_1        150250 non-null  int64
 19  entrega_doc_2        41212 non-null   str
 20  entrega_doc_3        150250 non-null  str
dtypes: float64(9), int64(6), object(2), str(4)
memory usage: 24.1+ MB

In [20]:
df_completo[["entrega_doc_1", "entrega_doc_2", "entrega_doc_3"]].isna().sum()

entrega_doc_1         0
entrega_doc_2    109038
entrega_doc_3         0
dtype: int64

In [22]:
df_completo.to_csv("../1.data/2.processed/dados_marco_abril.csv", index=False)